version: "3.8"
services:
  app:
    build: .
    command: uvicorn --host 0.0.0.0 --log-level debug --reload main:app
    image: splat-log
    ports:
    - "7860:7860"
    - "8000:8000"
    volumes:
    - ./:/app
  db:
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: 'splat'
      TZ: 'Asia/Tokyo'
    image: mysql:8.0
    ports:
    - "33306:3306"
    volumes:
    - db-data:/var/lib/mysql
volumes:
  db-data:
